version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.2

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: medium

    steps:
      - checkout

      - flutter/install_sdk_and_pub:
          version: 3.24.0

      - flutter/install_pub:
          cache-version: v1

      - run:
          name: Flutter pub get
          command: flutter pub get

      - run:
          name: Run unit tests
          command: flutter test

      - run:
          name: Build APK
          command: flutter build apk

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk

  alpha_stage:
     <<: *container_config
     steps:
       - checkout
       -
          run:
              command: bundle update fastlane && gem install bundler && bundle install
              name: configure build
       -
          restore_cache:
               <<: *general_cache_key
       -
          run:
               name: "Install Firebase CLI"
               command: |
                  curl -sL firebase.tools | bash
       -
          run:
               name: "Deploy alpha build to Firebase"
               command: |
                   bundle exec fastlane stage 
                   flavor:alpha branch:${CIRCLE_BRANCH} 
                   app_id:$FIREBASE_APP_ID_ALPHA 
                   firebase_token:$FIREBASE_TOKEN