version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.2

jobs:
  test_and_build:
    executor:
      name: android/android-machine
      resource-class: medium

    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.24.0

      - flutter/install_pub:
          cache-version: v1

      - run:
          name: Flutter pub get
          command: flutter pub get

      - run:
          name: Run unit tests
          command: flutter test

      - run:
          name: Build APK
          command: flutter build apk

      # - store_artifacts:
      #     path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    executor:
      name: android/android-machine
      resource-class: medium
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.24.0
      - run:
          name: Install Bundler and Dependencies
          command: |
            gem install bundler  && \
            cd android && \
            bundle install
      - run:
          name: Update Fastlane
          command: |
            cd android && \
            bundle update fastlane
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "android/Gemfile.lock" }}
      - run:
          name: Install Firebase CLI
          command: |
            curl -sL firebase.tools | bash
      - run:
          name: Deploy_to_firebase_app_distributor
          command: |
            cd android && 
            bundle exec fastlane stage app_id_stag:$FIREBASE_APP_ID_STAGING app_id_prod:$FIREBASE_APP_ID_PROD firebase_token:$FIREBASE_TOKEN

workflows:
  version: 2
  build_tests_deploy:
    jobs:
      - deploy
      # # always runs
      # - test_and_build
      # # requires test_and_build to run successfully first
      # - deploy:
      #     requires:
      #       - test_and_build
