
default_platform(:android)

platform :android do
  
  lane :publish_to_firebase do |options|
    build_notes = "Environment: #{options[:flavor].capitalize}. Branch: #{options[:branch]}. Notes: #{options[:notes]}. Built by #{options[:author]}"
    gradle(task: "assembleRelease")
    firebase_app_distribution(
       app: "#{options[:app_id]}",
       groups: "name-of-your-test-group",
       release_notes: build_notes,
       apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
       firebase_cli_token: "#{options[:firebase_token]}"
    )
  end
end


