# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end

  desc "Stage and conditionally upload to Firebase"
  lane :stage do |options|
    commit = last_git_commit
    if options[:branch] != "develop" && commit[:message].downcase.include?("#upload") || options[:branch] == "master"
      release_type = "Release"

      commit_notes = ""
      if options[:branch] == "master"
        commit_notes = "Release candidate. #{commit[:message]}"
      else
        commit_notes = commit[:message].sub("#upload ", "")
      end

      # Upload build to Firebase
      sign_apk_lane(flavor: options[:flavor].capitalize, type: release_type)
      publish_to_firebase(
        flavor: options[:flavor],
        branch: options[:branch],
        notes: commit_notes,
        author: commit[:author],
        app_id: options[:app_id],
        firebase_token: options[:firebase_token]
      )
    end
  end
  
  lane :publish_to_firebase do |options|
    build_notes = "Environment: #{options[:flavor].capitalize}. Branch: #{options[:branch]}. Notes: #{options[:notes]}. Built by #{options[:author]}"
    firebase_app_distribution(
       app: "#{options[:app_id]}",
       testers: "name-of-your-test-group",
       release_notes: build_notes,
       android_artifact_path: "build/app/outputs/flutter-apk/app-release.apk",
       firebase_cli_token: "#{options[:firebase_token]}"
    )
  end
end


